//! Running commands in a site's docroot.
//!
//! Deliberately a **command runner**, not a full TTY: it streams stdout and
//! stderr from one command at a time. That covers what people actually reach a
//! terminal for here -- `wp plugin list`, `composer install`, `npm run build` --
//! without pretending to be a shell it is not. Anything interactive (vim, a
//! REPL, a prompt that waits for input) needs a real terminal, and
//! `terminal_command` opens one rather than hanging on a prompt nobody can see.

use crate::{paths, runtime, site::Site, wordpress, Error, Result};
use std::io::{BufRead, BufReader};
use std::process::{Command, Stdio};

/// The PATH a site's commands run with: its own PHP first, then the system.
///
/// A site on 8.1 must get 8.1 from `php`, not whatever is on the machine --
/// otherwise the version the terminal reports and the version serving the site
/// disagree, which is the exact confusion this tool exists to remove.
pub fn site_path(site: &Site) -> Result<String> {
    let php_dir = runtime::php_dir(&site.php_minor, "cli")?;
    let system = std::env::var("PATH").unwrap_or_else(|_| "/usr/bin:/bin".into());
    Ok(format!("{}:{system}", php_dir.display()))
}

/// A `wp` shim so the bundled WP-CLI is on PATH as a plain command.
fn ensure_wp_shim(site: &Site) -> Result<std::path::PathBuf> {
    let bin_dir = paths::root().join("bin");
    paths::mkdir_p(&bin_dir)?;
    let shim = bin_dir.join("wp");
    let php = runtime::php_binary(&site.php_minor)?;
    let phar = wordpress::wp_cli_path();
    let body = format!(
        "#!/bin/sh\n# Generated by QuickWP. Runs WP-CLI on this site's own PHP.\nexec {:?} -d allow_url_fopen=1 {:?} \"$@\"\n",
        php, phar
    );
    std::fs::write(&shim, body).map_err(|e| Error::Io {
        path: shim.clone(),
        source: e,
    })?;
    use std::os::unix::fs::PermissionsExt;
    let mut perm = std::fs::metadata(&shim)
        .map_err(|e| Error::Io { path: shim.clone(), source: e })?
        .permissions();
    perm.set_mode(0o755);
    let _ = std::fs::set_permissions(&shim, perm);
    Ok(bin_dir)
}

#[derive(Debug, Clone, serde::Serialize)]
pub struct ExecLine {
    pub stream: String,
    pub text: String,
}

/// Run one command in the site's docroot, streaming each line to `on_line`.
///
/// Returns the exit code. A non-zero exit is a result, not an error: the
/// caller wants the output either way.
pub fn run_streaming(
    site: &Site,
    command: &str,
    mut on_line: impl FnMut(ExecLine) + Send,
) -> Result<i32> {
    if command.trim().is_empty() {
        return Err(Error::other("Nothing to run."));
    }

    let bin_dir = ensure_wp_shim(site).unwrap_or_else(|_| paths::root().join("bin"));
    let path = format!("{}:{}", bin_dir.display(), site_path(site)?);

    let mut child = Command::new("/bin/sh")
        .arg("-lc")
        .arg(command)
        .current_dir(&site.docroot)
        .env("PATH", path)
        .env("QUICKWP_SITE", &site.domain)
        // Laravel's env precedence means these outrank a project's .env, which
        // is what makes its mail catchable at all.
        .envs(crate::mail::laravel_env())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .stdin(Stdio::null()) // no TTY: a command that prompts must not hang
        .spawn()
        .map_err(|e| Error::Io {
            path: site.docroot.clone().into(),
            source: e,
        })?;

    let stdout = child.stdout.take();
    let stderr = child.stderr.take();

    // stderr on a thread so a chatty build does not deadlock on a full pipe.
    let err_handle = stderr.map(|e| {
        std::thread::spawn(move || {
            BufReader::new(e)
                .lines()
                .map_while(std::result::Result::ok)
                .collect::<Vec<_>>()
        })
    });

    if let Some(out) = stdout {
        for line in BufReader::new(out).lines().map_while(std::result::Result::ok) {
            on_line(ExecLine {
                stream: "stdout".into(),
                text: line,
            });
        }
    }

    if let Some(h) = err_handle {
        for line in h.join().unwrap_or_default() {
            on_line(ExecLine {
                stream: "stderr".into(),
                text: line,
            });
        }
    }

    let status = child.wait().map_err(|e| Error::Io {
        path: "wait".into(),
        source: e,
    })?;
    Ok(status.code().unwrap_or(-1))
}

/// The command that opens a real terminal in the docroot, for anything
/// interactive this runner cannot host.
pub fn terminal_command(site: &Site) -> Result<String> {
    let bin_dir = ensure_wp_shim(site).unwrap_or_else(|_| paths::root().join("bin"));
    Ok(format!(
        "cd {:?} && export PATH={:?}:{:?}:$PATH",
        site.docroot,
        bin_dir.display().to_string(),
        runtime::php_dir(&site.php_minor, "cli")?.display().to_string(),
    ))
}

/// Open Terminal.app in the site's docroot with its PHP and `wp` on PATH.
pub fn open_terminal(site: &Site) -> Result<()> {
    let script = terminal_command(site)?;
    let osa = format!(
        "tell application \"Terminal\"\n activate\n do script \"{}\"\nend tell",
        script.replace('\\', "\\\\").replace('"', "\\\"")
    );
    std::process::Command::new("/usr/bin/osascript")
        .arg("-e")
        .arg(osa)
        .spawn()
        .map_err(|e| Error::Io {
            path: "/usr/bin/osascript".into(),
            source: e,
        })?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn a_site(dir: &std::path::Path) -> Site {
        Site {
            id: 1,
            name: "t".into(),
            domain: "t.test".into(),
            docroot: dir.to_string_lossy().into(),
            kind: "php".into(),
            php_minor: "8.3".into(),
            server: "nginx".into(),
            enabled: true,
            is_linked: true,
            xdebug: false,
            db_engine: None,
            db_name: None,
            aliases: vec![],
        }
    }

    #[test]
    fn output_streams_and_the_exit_code_is_returned() {
        let dir = std::env::temp_dir().join("quickwp-exec-test");
        std::fs::create_dir_all(&dir).unwrap();
        let mut lines = Vec::new();
        let code = run_streaming(&a_site(&dir), "echo hello; echo oops >&2", |l| lines.push(l)).unwrap();
        assert_eq!(code, 0);
        assert!(lines.iter().any(|l| l.stream == "stdout" && l.text == "hello"));
        assert!(lines.iter().any(|l| l.stream == "stderr" && l.text == "oops"));
    }

    #[test]
    fn a_failing_command_returns_its_code_rather_than_erroring() {
        let dir = std::env::temp_dir().join("quickwp-exec-fail");
        std::fs::create_dir_all(&dir).unwrap();
        let code = run_streaming(&a_site(&dir), "exit 3", |_| {}).unwrap();
        assert_eq!(code, 3, "a non-zero exit is a result the caller wants, not an error");
    }

    #[test]
    fn commands_run_in_the_docroot() {
        let dir = std::env::temp_dir().join("quickwp-exec-cwd");
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("marker.txt"), "x").unwrap();
        let mut lines = Vec::new();
        run_streaming(&a_site(&dir), "ls", |l| lines.push(l)).unwrap();
        assert!(lines.iter().any(|l| l.text.contains("marker.txt")));
    }

    #[test]
    fn an_empty_command_is_refused() {
        let dir = std::env::temp_dir().join("quickwp-exec-empty");
        std::fs::create_dir_all(&dir).unwrap();
        assert!(run_streaming(&a_site(&dir), " ", |_| {}).is_err());
    }
}
