//! Real terminal sessions.
//!
//! A pseudo-terminal, not a command runner: the child gets a TTY, so it line-
//! edits, paints colour, draws a full-screen editor and asks questions that can
//! be answered. `vim`, `top`, a Composer prompt and `wp shell` all work.
//!
//! Sessions are keyed by id and outlive individual commands -- the shell stays
//! open the way a terminal does. They are killed when the app quits, because a
//! shell with no window attached is a process nobody can see.

use crate::{paths, runtime, site::Site, wordpress, Error, Result};
use portable_pty::{CommandBuilder, MasterPty, NativePtySystem, PtyPair, PtySize, PtySystem};
use std::collections::HashMap;
use std::io::{Read, Write};
use std::sync::{Arc, Mutex};

pub struct Session {
    pair: PtyPair,
    writer: Box<dyn Write + Send>,
    child: Box<dyn portable_pty::Child + Send + Sync>,
}

#[derive(Clone, Default)]
pub struct Ptys {
    sessions: Arc<Mutex<HashMap<String, Session>>>,
}

/// A `wp` shim, so the bundled WP-CLI is a plain command on PATH.
fn ensure_wp_shim(site: &Site) -> Result<std::path::PathBuf> {
    let bin_dir = paths::root().join("bin");
    paths::mkdir_p(&bin_dir)?;
    let shim = bin_dir.join("wp");
    let php = runtime::php_binary(&site.php_minor)?;
    let phar = wordpress::wp_cli_path();
    std::fs::write(
        &shim,
        format!(
            "#!/bin/sh\n# Generated by Nexora. Runs WP-CLI on this site's own PHP.\nexec {php:?} -d allow_url_fopen=1 {phar:?} \"$@\"\n"
        ),
    )
    .map_err(|e| Error::Io { path: shim.clone(), source: e })?;
    use std::os::unix::fs::PermissionsExt;
    let mut perm = std::fs::metadata(&shim)
        .map_err(|e| Error::Io { path: shim.clone(), source: e })?
        .permissions();
    perm.set_mode(0o755);
    let _ = std::fs::set_permissions(&shim, perm);
    Ok(bin_dir)
}

impl Ptys {
    pub fn new() -> Self {
        Self::default()
    }

    /// Open a shell in a site's docroot. `on_output` receives bytes as they
    /// arrive; it runs on a reader thread until the shell exits.
    pub fn open(
        &self,
        id: &str,
        site: &Site,
        cols: u16,
        rows: u16,
        on_output: impl Fn(String) + Send + 'static,
        on_exit: impl Fn() + Send + 'static,
    ) -> Result<()> {
        if self.sessions.lock().map(|s| s.contains_key(id)).unwrap_or(false) {
            return Ok(());
        }

        let pty = NativePtySystem::default();
        let pair = pty
            .openpty(PtySize {
                rows,
                cols,
                pixel_width: 0,
                pixel_height: 0,
            })
            .map_err(|e| Error::other(format!("could not open a terminal: {e}")))?;

        let shell = std::env::var("SHELL").unwrap_or_else(|_| "/bin/zsh".into());
        let mut cmd = CommandBuilder::new(shell);
        cmd.cwd(&site.docroot);

        // The site's own PHP first, so `php -v` in this window agrees with what
        // is serving the site. A shell that reports a different version than
        // the pool is the exact confusion this tool exists to remove.
        let bin_dir = ensure_wp_shim(site).unwrap_or_else(|_| paths::root().join("bin"));
        let php_dir = runtime::php_dir(&site.php_minor, "cli")?;
        let system_path = std::env::var("PATH").unwrap_or_else(|_| "/usr/bin:/bin".into());
        cmd.env(
            "PATH",
            format!("{}:{}:{system_path}", bin_dir.display(), php_dir.display()),
        );
        cmd.env("NEXORA_SITE", &site.domain);
        cmd.env("TERM", "xterm-256color");
        // Laravel reads these from the environment ahead of .env, which is what
        // makes mail sent from this shell catchable too.
        for (k, v) in crate::mail::laravel_env() {
            cmd.env(k, v);
        }

        let child = pair
            .slave
            .spawn_command(cmd)
            .map_err(|e| Error::other(format!("could not start a shell: {e}")))?;

        let mut reader = pair
            .master
            .try_clone_reader()
            .map_err(|e| Error::other(format!("could not read the terminal: {e}")))?;
        let writer = pair
            .master
            .take_writer()
            .map_err(|e| Error::other(format!("could not write to the terminal: {e}")))?;

        let sessions = self.sessions.clone();
        let key = id.to_string();
        std::thread::spawn(move || {
            let mut buf = [0u8; 8192];
            loop {
                match reader.read(&mut buf) {
                    Ok(0) => break,
                    Ok(n) => on_output(String::from_utf8_lossy(&buf[..n]).into_owned()),
                    Err(_) => break,
                }
            }
            // The shell exited (a user typed `exit`, or it crashed). Drop the
            // session so the id can be reused rather than pointing at a corpse.
            if let Ok(mut s) = sessions.lock() {
                s.remove(&key);
            }
            on_exit();
        });

        self.sessions
            .lock()
            .map_err(|_| Error::other("pty lock poisoned"))?
            .insert(id.to_string(), Session { pair, writer, child });
        Ok(())
    }

    /// Send keystrokes. This is what makes it a terminal rather than a runner:
    /// a prompt can be answered.
    pub fn write(&self, id: &str, data: &str) -> Result<()> {
        let mut s = self.sessions.lock().map_err(|_| Error::other("pty lock poisoned"))?;
        let session = s
            .get_mut(id)
            .ok_or_else(|| Error::other("that terminal is not open"))?;
        session
            .writer
            .write_all(data.as_bytes())
            .map_err(|e| Error::Io { path: id.into(), source: e })?;
        session.writer.flush().ok();
        Ok(())
    }

    /// Tell the child its window changed, so full-screen programs repaint at
    /// the right size instead of wrapping at 80 columns forever.
    pub fn resize(&self, id: &str, cols: u16, rows: u16) -> Result<()> {
        let s = self.sessions.lock().map_err(|_| Error::other("pty lock poisoned"))?;
        let session = s.get(id).ok_or_else(|| Error::other("that terminal is not open"))?;
        session
            .pair
            .master
            .resize(PtySize { rows, cols, pixel_width: 0, pixel_height: 0 })
            .map_err(|e| Error::other(format!("resize failed: {e}")))
    }

    pub fn close(&self, id: &str) -> Result<bool> {
        let mut s = self.sessions.lock().map_err(|_| Error::other("pty lock poisoned"))?;
        match s.remove(id) {
            Some(mut session) => {
                let _ = session.child.kill();
                let _ = session.child.wait();
                Ok(true)
            }
            None => Ok(false),
        }
    }

    pub fn is_open(&self, id: &str) -> bool {
        self.sessions.lock().map(|s| s.contains_key(id)).unwrap_or(false)
    }

    /// Close every session. A shell with no window attached is a process
    /// nobody can see, so quitting takes them all.
    pub fn close_all(&self) {
        let ids: Vec<String> = self
            .sessions
            .lock()
            .map(|s| s.keys().cloned().collect())
            .unwrap_or_default();
        for id in ids {
            let _ = self.close(&id);
        }
    }
}

/// Keeps `MasterPty` object-safe usage honest across threads.
fn _assert_send(_: &dyn MasterPty) {}
