#!/usr/bin/env bash
# Pin the non-PHP runtime components by SHA-256.
#
# Same rule as scripts/pin-runtimes.sh: the hash is taken from the published
# asset, never from a local build.
#
# Usage:  scripts/pin-services.sh [aarch64|x86_64|both]
set -euo pipefail

ARCHES="${1:-aarch64}"
[ "$ARCHES" = "both" ] && ARCHES="aarch64 x86_64"

# MySQL publishes official macOS tarballs. MariaDB does NOT publish a macOS
# bintar, so supporting it means producing a reproducible build of our own --
# tracked, not claimed.
MYSQL_VERSIONS=("8.4.9" "8.0.44")
[ "${SKIP_MYSQL:-}" = "1" ] && MYSQL_VERSIONS=()
WPCLI_VERSION="2.12.0"

hash_url() { curl -fsSL "$1" | shasum -a 256 | cut -d' ' -f1; }
mysql_arch() { [ "$1" = "aarch64" ] && echo "arm64" || echo "x86_64"; }

echo "# Generated by scripts/pin-services.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo

for arch in $ARCHES; do
  ma="$(mysql_arch "$arch")"
  for v in ${MYSQL_VERSIONS[@]+"${MYSQL_VERSIONS[@]}"}; do
    series="${v%.*}"
    url="https://cdn.mysql.com/Downloads/MySQL-${series}/mysql-${v}-macos15-${ma}.tar.gz"
    >&2 echo "hashing mysql ${v} ${arch} (large) ..."
    sum="$(hash_url "$url")" || { >&2 echo "  FAILED $url"; continue; }
    echo "[[mysql]]"
    echo "series = \"$series\""
    echo "version = \"$v\""
    echo "arch   = \"$arch\""
    echo "url    = \"$url\""
    echo "sha256 = \"$sum\""
    echo
  done
done

MAILPIT_VERSION="1.31.1"
CLOUDFLARED_VERSION="2026.8.3"

go_arch() { [ "$1" = "aarch64" ] && echo "arm64" || echo "amd64"; }

for arch in $ARCHES; do
  ga="$(go_arch "$arch")"

  url="https://github.com/axllent/mailpit/releases/download/v${MAILPIT_VERSION}/mailpit-darwin-${ga}.tar.gz"
  >&2 echo "hashing mailpit ${MAILPIT_VERSION} ${arch} ..."
  sum="$(hash_url "$url")"
  echo "[[mailpit]]"
  echo "version = \"$MAILPIT_VERSION\""
  echo "arch   = \"$arch\""
  echo "url    = \"$url\""
  echo "sha256 = \"$sum\""
  echo

  url="https://github.com/cloudflare/cloudflared/releases/download/${CLOUDFLARED_VERSION}/cloudflared-darwin-${ga}.tgz"
  >&2 echo "hashing cloudflared ${CLOUDFLARED_VERSION} ${arch} ..."
  sum="$(hash_url "$url")"
  echo "[[cloudflared]]"
  echo "version = \"$CLOUDFLARED_VERSION\""
  echo "arch   = \"$arch\""
  echo "url    = \"$url\""
  echo "sha256 = \"$sum\""
  echo
done

# WP-CLI is architecture-independent: one phar run by whichever PHP the site uses.
url="https://github.com/wp-cli/wp-cli/releases/download/v${WPCLI_VERSION}/wp-cli-${WPCLI_VERSION}.phar"
>&2 echo "hashing wp-cli ${WPCLI_VERSION} ..."
sum="$(hash_url "$url")"
echo "[[wpcli]]"
echo "version = \"$WPCLI_VERSION\""
echo "url    = \"$url\""
echo "sha256 = \"$sum\""
