#!/usr/bin/env bash
# Pin Nexora runtime components by SHA-256.
#
# Every binary Nexora runs is verified against a checksum compiled into the
# app. That pin is what makes a compromised download host unable to reach an
# installed user, so it must be taken from the published asset -- never from a
# local build.
#
# Usage:  scripts/pin-runtimes.sh [aarch64|x86_64|both]
# Output: TOML on stdout, paste into core/src/runtime/pins.toml
set -euo pipefail

ARCHES="${1:-aarch64}"
[ "$ARCHES" = "both" ] && ARCHES="aarch64 x86_64"

PHP_MINORS=("8.0.30" "8.1.34" "8.2.32" "8.3.32" "8.4.23" "8.5.8")
# The `bulk` variant, not `common`: common ships pdo_mysql but NOT mysqli, and
# WordPress requires mysqli specifically. bulk also carries intl, imagick,
# sodium and OPcache -- the extension set a real WordPress site expects.
BASE="https://dl.static-php.dev/static-php-cli/bulk"

hash_url() {
  # Stream the asset through sha256 without keeping it on disk.
  curl -fsSL "$1" | shasum -a 256 | cut -d' ' -f1
}

echo "# Generated by scripts/pin-runtimes.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "# Hashes are taken from the published asset, never a local build."
echo

for arch in $ARCHES; do
  for full in "${PHP_MINORS[@]}"; do
    minor="${full%.*}"
    for kind in fpm cli; do
      url="$BASE/php-${full}-${kind}-macos-${arch}.tar.gz"
      >&2 echo "hashing php ${full} ${kind} ${arch} ..."
      sum="$(hash_url "$url")" || { >&2 echo "  FAILED $url"; continue; }
      echo "[[php]]"
      echo "minor  = \"$minor\""
      echo "patch  = \"$full\""
      echo "kind   = \"$kind\""
      echo "arch   = \"$arch\""
      echo "url    = \"$url\""
      echo "sha256 = \"$sum\""
      echo
    done
  done
done
